### ISSUE TITLE
Expected answers of task 7 are wrong

### ISSUE THREAD

**Issue by NoHomey** [triffon/up-2016-17-hw-tests#2]
Looking into [the image for task7](https://docs.google.com/document/d/1ATu-xPAL7cFYPAey7N03qQKNi3jGkTX0_GnvLkMC-fE/edit) shows that when the input is `0.5 -1.5` the answer should be `Evil` instead of `Good` and when the input is `2.5 3` the expected output should be `Good` instead of `Evil`.

**Comment by triffon** [comment]
Напълно си прав, отговорите в базовите тестове бяха обърнати.
